on:
  push:
    branches:
    - feature/*

env:
  AZURE_WEBAPP_NAME: azwe-webapp-d01-auth
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '14.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Az login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
    - name: Get key vault secrets
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ secrets.DEV_KEY_VAULT_NAME }}
        secrets: '*'
      id: kv
    - name: Create .env file
      run: |
        cat << EOF >> .env
        NODE_ENV = development
        SERVER_PORT = ${{ steps.kv.outputs.server-port }}
        REDIS_URL = ${{ steps.kv.outputs.redis-url }}
        REDIS_KEY = ${{ steps.kv.outputs.redis-key }}
        CORS_ORIGIN = ${{ steps.kv.outputs.cors-origin }}
        SESSION_SECRET = ${{ steps.kv.outputs.session-secret }}

        TYPEORM_CONNECTION = mariadb
        TYPEORM_LOGGING = true
        TYPEORM_ENTITIES = src/entities/**/*.ts
        TYPEORM_ENTITIES = src/migrations/**/*.ts
        TYPEORM_HOST = ${{ steps.kv.outputs.typeorm-host }}
        TYPEORM_USERNAME = ${{ steps.kv.outputs.typeorm-username }}
        TYPEORM_PASSWORD = ${{ steps.kv.outputs.typeorm-password }}
        TYPEORM_DATABASE = ${{ steps.kv.outputs.typeorm-database }}
        TYPEORM_PORT = ${{ steps.kv.outputs.typeorm-port }}
        EOF
    - name: Build
      run: |
        yarn
        yarn build
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
