on:
  push:
    branches:
    - feature/*

env:
  APP_NAME: auth-app-backend
  AZURE_WEBAPP_NAME: azwe-backend-t01-auth

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Az login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Get key vault secrets
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: ${{ secrets.KEY_VAULT_NAME }}
        secrets: '*'
      id: kv
    - name: Create .env file
      run: |
        cat << EOF >> .env
        NODE_ENV = development
        PORT = ${{ steps.kv.outputs.server-port }}
        REDIS_URL = ${{ steps.kv.outputs.redis-url }}
        REDIS_KEY = ${{ steps.kv.outputs.redis-key }}
        CORS_ORIGIN = ${{ steps.kv.outputs.cors-origin }}
        SESSION_SECRET = ${{ steps.kv.outputs.session-secret }}

        TYPEORM_CONNECTION = mariadb
        TYPEORM_LOGGING = true
        TYPEORM_ENTITIES = dist/entities/**/*.js
        TYPEORM_MIGRATIONS = dist/migrations/**/*.js
        TYPEORM_HOST = ${{ steps.kv.outputs.typeorm-host }}
        TYPEORM_USERNAME = ${{ steps.kv.outputs.typeorm-username }}
        TYPEORM_PASSWORD = ${{ steps.kv.outputs.typeorm-password }}
        TYPEORM_DATABASE = ${{ steps.kv.outputs.typeorm-database }}
        TYPEORM_PORT = ${{ steps.kv.outputs.typeorm-port }}
        EOF
    - name: Docker build
      run: |
        docker build -t ${{ secrets.REGISTRY_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }} .
        docker tag ${{ secrets.REGISTRY_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }} ${{ secrets.REGISTRY_SERVER }}/${{ env.APP_NAME }}:latest
    - name: Docker push
      run: |
        az acr login --name ${{ secrets.REGISTRY_SERVER }}
        docker push ${{ secrets.REGISTRY_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_SERVER }}/${{ env.APP_NAME }}:latest
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        images: '${{ secrets.REGISTRY_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }}'
    - name: Az logout
      run: |
        az logout